name: Publish Postgres Cluster Helm Chart to GitHub Pages

on:
  push:
    branches:
      - main # Replace with the branch you want to trigger this workflow

jobs:
  publish:
    name: Publish Helm Chart
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-postgrescluster

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Helm
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.0 # Specify Helm version

    # Step 3: Extract Chart Version
    - name: Extract Helm Chart Version
      id: chart_version
      run: |
        CHART_NAME=$(yq '.name' ./helm/postgres/Chart.yaml)
        CHART_VERSION=$(yq '.version' ./helm/postgres/Chart.yaml)
        echo "chart_name=${CHART_NAME}" >> $GITHUB_ENV
        echo "chart_version=${CHART_VERSION}" >> $GITHUB_ENV

    # Step 4: Package the Helm chart
    - name: Package Helm Chart
      run: |
        mkdir -p packaged
        helm package ./helm/postgres --destination ./packaged
      env:
        HELM_EXPERIMENTAL_OCI: 1

    # Step 5: Generate Helm repository index
    - name: Generate Helm Repository Index
      run: |
        helm repo index ./packaged --url https://skydevsorg.github.io/postgres-operator/

    # Step 6: Create Git Tag
    - name: Create Git Tag
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag "${chart_name}-${chart_version}"
        git push origin "${chart_name}-${chart_version}"
      env:
        chart_name: ${{ env.chart_name }}
        chart_version: ${{ env.chart_version }}

    # Step 7: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./packaged

